# External dependencies managed by chezmoi
# These files/directories are downloaded from external sources
# and refreshed automatically based on refreshPeriod

# Zsh plugins - downloaded from GitHub instead of via Homebrew
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-history-substring-search"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-history-substring-search/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

# Neovim plugin manager (vim-plug)
[".local/share/nvim/site/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"

# Tmux Plugin Manager (TPM)
[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm.git"
    refreshPeriod = "168h"

# Catppuccin tmux theme - pinned to v2.1.3
[".config/tmux/plugins/catppuccin/tmux"]
    type = "git-repo"
    url = "https://github.com/catppuccin/tmux.git"
    [".config/tmux/plugins/catppuccin/tmux".clone]
        args = ["-b", "v2.1.3"]
